name: Jeff Free
description: The musings, ventures, and zines of Jeff Free — a full stack designer from Melbourne.
url: http://xn--dwg.cf/
markdown: kramdown
permalink: pretty
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
